[project]
site_name = "–ü–µ—à–∞—á–∫–æ"
site_description = "–ü–µ—à–∞—á–∫–æ -- –∏–Ω–∏—Ü–∏–∞—Ç–∏–≤–∞ –∑–∞ —á–∏—Å—Ç –≤—ä–∑–¥—É—Ö –∏ –∑–¥—Ä–∞–≤–µ."
site_author = "–î–∏–º–∏—Ç—ä—Ä –î–∏–º–∏—Ç—Ä–æ–≤ (drdv.net)"
site_url = "https://peshachko.bg/"
repo_url = "https://github.com/peshachko/peshachko.github.io"
edit_uri = "edit/main/docs/"
copyright = """&copy; 2025 –ù–ü–û –ü–µ—à–∞—á–∫–æ (contact@peshachko.bg)"""
extra_css = ["stylesheets/extra.css", "stylesheets/glightbox.min.css"]

nav = [
  {"–ù–∞—á–∞–ª–æ" = [
    "index.md",
	{"üßí –ö—ä–º –¥–µ—Ü–∞—Ç–∞" = "poems/20260105_antoaneta_marinova"},
  ]},
  {"–ù–ü–û" = "ngo.md"},
  {"–ù–∞—à–∏—è—Ç –≥—Ä–∞–¥" = "environment.md"},
  {"–°—ä–±–∏—Ç–∏—è" = [
    {"–°—ä–±–∏—Ç–∏—è" = "events/events.md"},
    {"–ü—Ä–µ–¥—Å—Ç–æ—è—â–∏" = [
	  {"1 –§–µ–≤—Ä—É–∞—Ä–∏ 2026 (–ì—Ä–µ–Ω–æ–±—ä–ª)" = "events/20260201-grenoble.md"},
	  {"14 –§–µ–≤—Ä—É–∞—Ä–∏ 2026 (–°–æ—Ñ–∏—è)" = "events/20260214-sofia.md"},
	  {"28 –§–µ–≤—Ä—É–∞—Ä–∏ 2026 (–°–æ—Ñ–∏—è)" = "events/20260228-sofia.md"},
	]},
	{"–ú–∏–Ω–∞–ª–∏" = [
	  {"31 –Ø–Ω—É–∞—Ä–∏ 2026 (–°–æ—Ñ–∏—è)" = "events/20260131-sofia.md"},
	  {"31 –Ø–Ω—É–∞—Ä–∏ 2026 (–í–∞—Ä–Ω–∞)" = "events/20260131-varna.md"},
	  {"17 –Ø–Ω—É–∞—Ä–∏ 2026 (–°–æ—Ñ–∏—è)" = "events/20260117-sofia.md"},
	  {"22 –°–µ–ø—Ç–µ–º–≤—Ä–∏ 2025 (–°–æ—Ñ–∏—è)" = "events/20250922-sofia.md"},
	  {"12 –ê–≤–≥—É—Å—Ç 2025 (–°–æ—Ñ–∏—è)" = "events/20250812-sofia.md"}
	]},
  ]},
  {"–°—Ç–∏—Ö–æ–≤–µ" = [
    "poems/poems.md",
    {"2026" = [
	  {"&nbsp; –§–µ–≤—Ä—É–∞—Ä–∏" = [
	    {"(1) –ú–∞—Ä–∏–Ω–µ–ª–∞" = "poems/20260201_marinela.md"},
	  ]},
	  {"&nbsp; –Ø–Ω—É–∞—Ä–∏" = [
	    {"(19) –ú–∞—Ä–∏–Ω–µ–ª–∞" = "poems/20260119_marinela.md"},
	    {"(5) –ê–Ω—Ç–æ–∞–Ω–µ—Ç–∞ –ú–∞—Ä–∏–Ω–æ–≤–∞" = "poems/20260105_antoaneta_marinova.md"},
	  ]},
    ]},
	{"2025" = [
	  {"&nbsp; –î–µ–∫–µ–º–≤—Ä–∏" = [
	    {"(25) –¢–∞–Ω—è –≤–∞–Ω –î–∞–π–∫" = "poems/20251225_tanya_vandijk.md"},
	    {"(24) –ú–∞—Ä–∏–Ω–µ–ª–∞" = "poems/20251224_marinela.md"},
	  ]},
	  {"&nbsp; –°–µ–ø—Ç–µ–º–≤—Ä–∏" = [
	    {"(16)<sup>a</sup> –¢–∞–Ω—è –≤–∞–Ω –î–∞–π–∫" = "poems/20250916a_tanya_vandijk.md"},
	    {"(16)<sup>b</sup> –¢–∞–Ω—è –≤–∞–Ω –î–∞–π–∫" = "poems/20250916b_tanya_vandijk.md"},
		{"(12) –¢–∞–Ω—è –≤–∞–Ω –î–∞–π–∫" = "poems/20250912_tanya_vandijk.md"},
		{"(10) –¢–∞–Ω—è –≤–∞–Ω –î–∞–π–∫" = "poems/20250910_tanya_vandijk.md"},
	    {"(5) –¢–∞–Ω—è –≤–∞–Ω –î–∞–π–∫" = "poems/20250905_tanya_vandijk.md"},
	  ]},
	  {"&nbsp; –ê–≤–≥—É—Å—Ç" = [
	    {"(24) –ú–∞—Ä–∏–Ω–µ–ª–∞" = "poems/20250824_marinela.md"},
	  ]},
    ]},
  ]},
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
language = "bg"
favicon = "img/logo.png"
logo = "img/logo.png"
custom_dir = "docs/overrides"

features = [
    # "announce.dismiss",
	# "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    # "navigation.expand",
    # "navigation.footer",
    "navigation.indexes",
    # "navigation.instant",
    # "navigation.instant.prefetch",
    # "navigation.instant.progress",
    # "navigation.path",
    # "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    # "toc.follow",
    # "toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.extra]
generator = false

[project.extra.analytics]
provider = "google"
property = "G-MPZCVSVPZM"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/peshachko"

[[project.extra.social]]
icon = "fontawesome/brands/facebook"
link = "https://www.facebook.com/share/1ap91aSfj3"

[[project.extra.social]]
icon = "fontawesome/brands/instagram"
link = "https://www.instagram.com/peshachko"

[[project.extra.social]]
icon = "fontawesome/solid/paper-plane"
link = "mailto:contact@peshachko.bg"

[[project.extra_javascript]]
path = "javascripts/glightbox.min.js"

[[project.extra_javascript]]
path = "javascripts/glightbox_load.js"
type = "module"

# -----------------------------------------------------
# custom config variables
# -----------------------------------------------------

[[project.extra.maps_javascript]]
path = "javascripts/leaflet.js"

[[project.extra.maps_javascript]]
path = "javascripts/maps_show_routs.js"

[[project.extra.maps_css]]
path = "stylesheets/leaflet.css"

[[project.extra.maps_css]]
path = "stylesheets/maps.css"

# -----------------------------------------------------
# default extensions
# -----------------------------------------------------
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
# -----------------------------------------------------
# extra extensions
# -----------------------------------------------------
[project.markdown_extensions.pymdownx.snippets]